version: '3'
services:

  review:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $REVIEW_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  prod:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $PROD_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  beta:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $BETA_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
