version: '3'
services:
  web:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: '$GITLAB_HOST'
      networks:
        - web
      volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'
      ports:
        - '22:22'

networks:
  web:
