version: '2'
services:
  docker:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    scale: $GITLAB_RUNNER_DOCKER_SCALE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/gitlab-runner
