version: '2'
services:
  docker:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    networks:
      - system_gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/gitlab-runner

    extra_hosts:
      - "$GITLAB_REGISTRY_HOST:$GITLAB_IP"
      - "$GITLAB_HOST:$GITLAB_IP"

networks:
  system_gitlab:
    external:
      name: system_gitlab
