version: '3'
services:
  bootstrapper:
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $BACKUPDIR:$BACKUPDIR
      - templates:/templates
      - ssl:/ssl
    build:
      context: ./
      dockerfile: Dockerfile
volumes:
  templates:
  ssl: