version: '2'
services:
  bootstrapper:
    image: bootstrapper_system
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $LIVEDIR
      - $SSL_BASEDIR
      - $BACKUPDIR:$BACKUPDIR
