version: '3'
services:
  bootstrapper:
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SEED_DIR:/seed
      - templates:/templates
      - synctemplates:/synctemplates
      - ssl:/ssl
      - gitlabConfig:/srv/gitlab/config
      - gitlabLogs:/srv/gitlab/log
      - gitlabData:/srv/gitlab/data
    build:
      context: ../
      dockerfile: system/Dockerfile
      # Uncomment following line to create a local System base Image
      # args:
      #   - IMAGE=bootstrapper_system

  web:
    image: nginx
    volumes:
      - templates:/etc/nginx/templates
      - ssl:/ssl
    network_mode: "host"

  sync:
    image: nginx
    volumes:
      - synctemplates:/etc/nginx/templates
    network_mode: "host"

  wizard:
    restart: always
    image: systembootstrapper/wizard
    # build:
    #   context: ../wizard

  gitlab:
    image: 'gitlab/gitlab-ce:12.10.6-ce.0'
    restart: always
    hostname: '$GITLAB_HOST'
    networks:
      - gitlab
    volumes:
      - gitlabConfig:/etc/gitlab
      - gitlabLogs:/var/log/gitlab
      - gitlabData:/var/opt/gitlab
      - $SEED_DIR:/seed
    ports:
      - '22:22'
      - '5050:5050'

volumes:
  templates:
  synctemplates:
  ssl:
  gitlabConfig:
  gitlabLogs:
  gitlabData:

networks:
  gitlab:
