version: '3'
services:
  bootstrapper:
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $BACKUPDIR:$BACKUPDIR
      - templates:/templates
      - ssl:/ssl
    build:
      context: ./
      dockerfile: Dockerfile

  web:
    image: nginx
    volumes:
      - templates:/etc/nginx/templates
      - ssl:$SSL_BASEDIR
    network_mode: "host"

volumes:
  templates:
  ssl: