version: '2'
services:
  system:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  bootstrapper:
    image: system_system
    working_dir: /system
    command: /bin/bash ./start.sh
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $LIVEDIR:$LIVEDIR
      - $SSL_BASEDIR:$SSL_BASEDIR
