version: '3'
services:
  bootstrapper:
    restart: always
    networks:
      - system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $BACKUPDIR:$BACKUPDIR
      - templates:/templates
      - synctemplates:/synctemplates
      - ssl:/ssl
    build:
      context: ./
      dockerfile: Dockerfile

  web:
    image: nginx
    volumes:
      - templates:/etc/nginx/templates
      - ssl:$SSL_BASEDIR
    network_mode: "host"

  sync:
    image: nginx
    volumes:
      - synctemplates:/etc/nginx/templates
    network_mode: "host"

  review:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $REVIEW_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  prod:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $PROD_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  beta:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $BETA_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  gitlab:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: '$GITLAB_HOST'
      networks:
        - system
      volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'
      ports:
        - '22:22'

volumes:
  templates:
  synctemplates:
  ssl:

networks:
  bootstrapper:
  system:
  runner:
  gitlab:
