version: '3'
services:
  bootstrapper:
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $BACKUPDIR:$BACKUPDIR
      - templates:/templates
      - synctemplates:/synctemplates
      - ssl:/ssl
      - gitlabHome:$GITLAB_HOME
    build:
      context: ./
      dockerfile: Dockerfile

  web:
    image: nginx
    volumes:
      - templates:/etc/nginx/templates
      - ssl:$SSL_BASEDIR
    network_mode: "host"

  sync:
    image: nginx
    volumes:
      - synctemplates:/etc/nginx/templates
    network_mode: "host"

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '$GITLAB_HOST'
    networks:
      - gitlab
    volumes:
      - ${gitlabHome}/config:/etc/gitlab
      - ${gitlabHome}/logs:/var/log/gitlab
      - ${gitlabHome}/data:/var/opt/gitlab
      - $BACKUPDIR:$BACKUPDIR

    ports:
      - '22:22'
volumes:
  templates:
  synctemplates:
  ssl:
  gitlabHome:

networks:
  gitlab: