version: '3'
services:
  bootstrapper:
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $BACKUPDIR:$BACKUPDIR
      - templates:/templates
      - synctemplates:/synctemplates
      - ssl:/ssl
    build:
      context: ./
      dockerfile: Dockerfile

  web:
    image: nginx
    volumes:
      - templates:/etc/nginx/templates
      - ssl:$SSL_BASEDIR
    network_mode: "host"

  sync:
    image: nginx
    volumes:
      - synctemplates:/etc/nginx/templates
    network_mode: "host"

  review:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $REVIEW_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  prod:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $PROD_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  beta:
    image: 'jwilder/nginx-proxy'
    restart: always
    scale: $BETA_SCALE
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  templates:
  synctemplates:
  ssl: