version: '3'
services:
  bootstrapper:
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $LIVEDIR
      - $SSL_BASEDIR
      - $BACKUPDIR:$BACKUPDIR
    build:
      context: ./
      dockerfile: Dockerfile
      args:
          - LIVEDIR=${LIVEDIR}