version: "3.8"
services:
  web:
    image: nginx
    volumes:
    - $NGINX_TEMPLATE_DIR:/etc/nginx/templates
    - $SSL_BASEDIR:$SSL_BASEDIR
    ports: [80, 443, 5050]
    networks:
      - bootstrapper_default
